### ISSUE TITLE
Create Error logs in SQL Server

### ISSUE THREAD

**Issue by gacosta1** [clemsonMakerspace/CATS#45]
create a new database that contains error logs with:
> First Name
> Last Name
> CUID
> MachineID
> MachineType
> Timestamp
> Error status being: 1 - not authorized, 2 - machine error, 3 - input device not found
**We can settle this as a team in the next team meeting**

**Comment by gacosta1** [comment]
Then at the end of the day at 12:00 AM or an automated file will be created with users who tried to use the machine but did not have permission/untrained or machine errors were found or etc....
Food for thought.

**Comment by ophilli** [comment]
We could call Twillio or Sendgrid to automatically notify admins when
authorization fails.

**Comment by gacosta1** [comment]
Yes!! I like that!

**Comment by r3cebarnett** [comment]
Pretty good idea. I'll quickly make a database for it right now because why
not.

**Comment by ophilli** [comment]
I think this belongs in the Events table. That's what they are - no reason to call a new table for them.

**Comment by gacosta1** [comment]
Sweeet thanks Maurice! I created one, but just append to the Events db

**Comment by ophilli** [comment]
MySQL is a relational database - it's good design to avoid duplicating unnecessary data.

We've already got a table of CUIDs, and MachineIDs. Those contain all the first name, last name, machine type info we need.

I would like to propose the following:

| CUID* | MachineID* | Timestamp* | Status |
| --- | --- | --- | --- |
| C12345678 | 001 | 1970-01-01 00:00:01 | 1 |
| C23456789 | 010 | 1970-01-01 00:00:01 | 2 |
| C34567890 | 100 | 1970-01-01 00:00:01 | 3 |

\* Denotes Primary Key

**Comment by gacosta1** [comment]
Seems clean and straight to the point. I like it. I see it has already been implemented. We're on the right path then.

**Comment by gacosta1** [comment]
Error Log for database complete. We just need to figure out what we're going to use to notify the Admin.

**Comment by ophilli** [comment]
Re-opened pending pull request with code changes that resolve this issue.

**Comment by ophilli** [comment]
Enhancement implemented in #53
