### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by gacosta1** [clemsonMakerspace/CATS#54]
Test code for functionality and correctness

**Comment by ophilli** [comment]
Any ideas on how we can break this up into more actionable items?

**Comment by gacosta1** [comment]
Elaborate on that please.

**Comment by ophilli** [comment]
I guess I need a "How to Unit Test for Dummies". Do we need a testing framework?

**Comment by r3cebarnett** [comment]
Will be working on it this week

**Comment by r3cebarnett** [comment]
Started writing nose tests. Check my progress in nose branch.
