### ISSUE TITLE
CATS HAT v2

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/CATS#63]
Currently our CATS shield is just that - a shield. The next step will be to convert it to a [HAT](https://www.raspberrypi.org/blog/introducing-raspberry-pi-hats/). This means that a connected Pi would be able to identify our CATS HAT and automatically configure the GPIOs and drivers we need for the board.

Please see the [tech specs](https://github.com/raspberrypi/hats).

- [x] #48 Commit CATS Alpha Hardware Designs
- [ ] #57 Solder Repair
- [x] #33 LED Anode 3v
- [ ] #64 ID EEPROM Programming

**Comment by mbgroom** [comment]
The new PCB will be designed by 2/03/17 if time permits. Only a few changes need to be made. We will need to order a few different headers for the new PCB design. While we wait on the PCBs to come in we will order the new:
*headers
*LEDs
*resistors
*clips
