### ISSUE TITLE
Remove Parameters from blinkKey()

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/CATS#68]
Check out line 49 in keypad.py and on_off.py

See #53 for more info.

**Comment by ophilli** [comment]
See #53 for more info

**Comment by r3cebarnett** [comment]
Sent pull request w/ fix. Commit ID: 0c97191

**Comment by ophilli** [comment]
@r3cebarnett Maurice - check out my comments on #70. Also check out how I reference the issue. You can type in commit IDs or just #theIssueNumber and GitHub will paste in a link.
