### ISSUE TITLE
Diagnose Relay Failure

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/CATS#69]
Yesterday I accidentally let the magic smoke out of one of the power switch tails. We'll need to investigate what happened and figure out how to prevent it from reoccurring.

**Comment by r3cebarnett** [comment]
After contacting the company that makes this, I received some help.

The message I received:

"Maurice,

Appears the MOV failed. The MOV in this unit is rated at 140 vac rms and is used to protect the relay contacts against power line surges and load spikes. This has happened only once before and that was because the unit was accidentally connected to 220 volt mains. Is there any possibility that that could have happened in this case? (Unit was used in a factory that normally tested equipment to be sent overseas and someone forgot to switch the links on the step-up transformer back to 120 vac from 220 vac.)

Steve"

**Comment by ophilli** [comment]
Maurice thanks for the prompt research into this issue!

* I was never informed of any 220vac outlets in the Watt 110 - therefore I think it's very unlikely that occurred.
    * I will test the outlets on that side of the room today to verify their voltages.
* The Powerswitch Tail should have been wired up as depicted [here.](https://github.com/clemsonMakerspace/CATS/blob/devel/Hardware/Alpha_Wiring%20Schematic_schem.pdf)
    * It is possible that the ```+in``` and ```-in``` pins on the relay were swapped - but that should have at most fed the relay with -3.3vdc
* Additionally we have extensively operated this relay with no load, for what that's worth.

**Comment by ophilli** [comment]
@ophilli It appears that there was 208vac in the Makerspace. The Power switch tail was connected to this circuit - which seems likely to be the point of failure.

I am following up with the Facilities Manager for the Watt Family Innovation Center to address this.

**Comment by ophilli** [comment]
Incident Report from January 18th, 2017
-----

Summary:

The Power Distribution Unit for our Print Pod is outputting 208vac, despite being rated for 120vac only. The outlets on this Power Distribution Unit are NELA 5-20R, which students expect to deliver 120vac. We had one student device fail catastrophically already.

The Power Distribution Unit is connected to what should be a 30A 120V circuit that was installed specifically for the Makerspace. Tim Howard has indicated that he will have an electrician brought out as soon as possible.

Extended Report:

On Friday a student connected a device (Powerswitch Tail II) to the Tripp Lite PDUMH30 power distribution unit (PDU) on the Print Pod. Upon closing the circuit this device experienced a catastrophic internal failure. No students were injured during this event, and the damaged device was immediately disconnected from power.

On Monday one of the students contacted the manufacturer of the device regarding the incident. The manufacturer stated that this type of failure has occurred only once before. In that incident the device was accidentally connected to a 220vac. 

On Tuesday, the first business day since the incident I inspected the circuit with a multimeter and found that the PDU was distributing 208vac. The PDU has a recommended electrical service of 30A 120V. It features NEMA 5-20R outlets, and a NEMA L5-30P input cable. Upon discovering that the PDU was outputting 208vac I immediately spoke with Tim Pruett, who helped me verify that my readings were correct. We then disconnected the PDU from the circuit.

We have over $3,600 in 120vac only equipment connected to this PDU, alongside another $20,000 in equipment that is rated to support 100-240vac. The potential property damage was extremely large if this had not been caught sooner. The possible injuries that could have occurred to a student are even more grave, and we are very lucky to have caught this with such little damage.

I spoke with Tim Howard late Tuesday afternoon and he agreed that the readings were abnormal, and he told me he would reach out to University Facilities and have an electrician brought out as soon as possible.

-----
![img_20170117_160650](https://cloud.githubusercontent.com/assets/964870/22133807/90b1fe76-de90-11e6-8140-b4d9829d81df.jpg)
![img_20170117_160652](https://cloud.githubusercontent.com/assets/964870/22133811/94eaca4a-de90-11e6-9936-70ac3900f84f.jpg)
![img_20170117_160946](https://cloud.githubusercontent.com/assets/964870/22133812/98d1c140-de90-11e6-8297-b6a15dc38849.jpg)
![img_20170117_160952](https://cloud.githubusercontent.com/assets/964870/22133813/9bb2cb02-de90-11e6-95f7-356485e867fb.jpg)

**Comment by ophilli** [comment]
Following the incident report I submitted above our Research Safety contact, as well as our faculty advisor requested that we discontinue use of all electrical circuits in the Makerspace until they were cleared by an Electrician.

The electricians inspected the space on January 18th, and January 19th. We were cleared to use the other circuits on the 19th. I have also been told that an electrician will be able to correct the faulty circuit tomorrow, the 20th.
