### ISSUE TITLE
Register on CATS Wordpress

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/CATS#79]
You should have received an email with the instructions - please fill it out and get your account setup.

If I've assigned this to you it's because you haven't setup your account.

**Comment by ophilli** [comment]
@JamacTheQuack just following up on this.

**Comment by r3cebarnett** [comment]
Bump

**Comment by ophilli** [comment]
I believe Josh was able to resolve his issue. @jamcmil please close this issue if that is the case.
