### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by ophilli** [clemsonMakerspace/CATS#81]
We should develop a [requirements.txt](https://devcenter.heroku.com/articles/python-pip) file that installs the dependencies for our application.

This requirements file will be utilized for continuous integration testing, and simplifying distribution.

It should supplant a decent chunk of Software/setup.sh

**Comment by AnshulMalik** [comment]
I would like to help.

**Comment by gacosta1** [comment]
My friend. Thanks for your interest but you cannot help us.

**Comment by ophilli** [comment]
@AnshulMalik You're more than welcome to submit a PR for any of the issues labeled [help wanted].

If you need any further clarification about an issue just ask!

**Comment by gacosta1** [comment]
@AnshulMalik If you need any insight on what's going to let us know.
