### ISSUE TITLE
Optional KeyPad

### ISSUE THREAD

**Issue by gacosta1** [clemsonMakerspace/CATS#87]

**Comment by r3cebarnett** [comment]
@ophilli can you explain to me the importance of this? Thanks.

**Comment by ophilli** [comment]
@r3cebarnett some members of our target market (university administrators, professors, etc.) did not see the value in 2FA when we initially demoed in Boston.

It does make the space more secure, but it obscures the utility and ease of use for some members of our target market. Additionally it represents additional bulk and cost that is not necessary for every university deployment.

**Comment by r3cebarnett** [comment]
We have started implementation of this. A very quick TL;DR: We're adding two columns to the SQL server that will allow us to check if the user wants to use 2fa or if 2fa is forced or if the keypad isn't even there. mach2fa and user2fa are the variables names that I will implement in the code and the SQL starting now. @jhord please note this change in the sql.

**Comment by gacosta1** [comment]
I have started implementing the issue this morning and made some good progress. Still waiting on the SQL fixes described in PR #104 and PR #121  to be merged to make the code look better.

**Comment by r3cebarnett** [comment]
Waiting for @gacosta1 to update this since the SQL code got fixed
